### ISSUE TITLE
Exception: "Trying to get property of non-object" when calling the constructor of Client

### ISSUE THREAD

**Issue by sc85** [eversign/eversign-php-sdk#1]
**PHP 7.1
eversign-php-sdk 1.0**

I simple initialize the Client class with API key and business id and I receive an exception in return "Trying to get property of non-object".

**Part of stack trace:**
`at Raven_Breadcrumbs_ErrorHandler->handleError(8, 'Trying to get property of non-object', '/home/vagrant/Code/server/vendor/eversign/eversign-php-sdk/sdk/Eversign/ApiRequest.php', 151, array('response' => object(Response), 'responseJson' => array(object(stdClass))))
in ApiRequest.php (line 151)

at ApiRequest->startRequest()
in Client.php (line 97)
[...]`

Checking line 151 of ApiRequest.php and adding a var_dump of $responseJson shows that it contains no key called "error" which causes the fault.

Changing line 151 to `if(array_key_exists('error', $responseJson)) {` seems to fix the error.

**Comment by dominikkukacka** [comment]
Thank you for bringing this to our attention!
We just released a bugfix for that problem in v1.0.1

Best,
Dominik
