### ISSUE TITLE
Document Canceled property not hydrated

### ISSUE THREAD

**Issue by Micsou** [eversign/eversign-php-sdk#10]
Hi
It seems that the APi Json Response send document is_canceled property with 2 L ...
And the object is not well hydrated. 

![2018-06-01_16h05_43](https://user-images.githubusercontent.com/4601910/40844993-aaf75c88-65b5-11e8-95c9-5b0b11a55770.png)

I have rewrited the $isCanceled property with 2 L and it seems to work but it would be nicer to correct the API Response. 

Thanks by advance
Michael

**Comment by dominikkukacka** [comment]
Thanks for the heads up!
We just pushed 1.9.0 which renames `isCanceled` to `isCancelled` to be consistent with the API.

**Comment by Micsou** [comment]
Quick reply ;)
Thanks!
