### ISSUE TITLE
Log history when document is reassigned

### ISSUE THREAD

**Issue by Micsou** [eversign/eversign-php-sdk#12]
Hi, 
I'm carrying on my tests. Have a small question about signer reassignement. 

When the first signer of a document reassign that document, the new signer takes the id of the original signer. In the Document logs, all operations seem to be done by same person : the new signer. We've lost the mark of the frist signer....

On the other hand, if I download the final document completed, i can see the correct logs which show well who reassigned who.

Is that a lack or a bug ? Thanks for your help. 
Michael

**Comment by dominikkukacka** [comment]
Sorry about the long response time. Could you provide us with a reduced test case?
