### ISSUE TITLE
Incorrect initialisation of CheckBox field

### ISSUE THREAD

**Issue by linux019** [eversign/eversign-php-sdk#14]
Because _width_ and _height_  are defined in parent class as private members, in order to set ones
it's need to call
```
parent::setWidth(14);
parent::setHeight(14);
```

https://github.com/eversign/eversign-php-sdk/blob/master/sdk/Eversign/CheckboxField.php#L63

**Comment by dominikkukacka** [comment]
Thanks for the issue. Either set it via parent, or better move the property to protected. Do you want to provide a pull request?

**Comment by linux019** [comment]
Basically all properties and methods of all classes should be defined as protected , because it's impossible to overload them due to inheritance rules in child models

**Comment by dominikkukacka** [comment]
Yes you are right about that one.

**Comment by dominikkukacka** [comment]
fixed in v1.10.2: https://packagist.org/packages/eversign/eversign-php-sdk#1.10.2
Thanks!
