### ISSUE TITLE
Checkbox not working

### ISSUE THREAD

**Issue by michaelgavan** [eversign/eversign-php-sdk#17]
I have set the value of checkbox to "1" but it does not check the box at all.
$checkboxField = new CheckboxField();
$checkboxField->setName('CheckboxField');
$checkboxField->setFileIndex(0);
$checkboxField->setPage(1);
$checkboxField->setX($x);
$checkboxField->setY($y);
$checkboxField->setValue("1");

**Comment by dominikkukacka** [comment]
We just pushed a fix which fixes the setting of the value: https://packagist.org/packages/eversign/eversign-php-sdk#1.11.1
