### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by linux019** [eversign/eversign-php-sdk#18]
1) Undefined property: stdClass::$code at ..../vendor/eversign/eversign-php-sdk/sdk/Eversign/ApiRequest.php:166) - https://github.com/eversign/eversign-php-sdk/blob/master/sdk/Eversign/ApiRequest.php#L166

2) there is a strange check or typo (it checks for success and throws an exception?)
```
        if(isset($responseJson->success)) {
            throw new \Exception('Webservice Error No ' . $responseJson->code . ' - Type: ' . $responseJson->type);
        }
```

 at https://github.com/eversign/eversign-php-sdk/blob/master/sdk/Eversign/ApiRequest.php#L165
for that response from API
```
array (
  'success' => false,
  'error' => 
  array (
    'code' => 0,
    'type' => 'missing_file_id',
  ),
) 
```

**Comment by dominikkukacka** [comment]
Hello and thanks for reporting that.
The error check is a bit counterintuitive, but the `success` field will only be set if it is false. so that works right now. I fixed it any way, as well as the code/type error.
Best, Dominik
