### ISSUE TITLE
Is it possible to get Embedded Requesting

### ISSUE THREAD

**Issue by SuperIbm** [eversign/eversign-php-sdk#25]
Hello. As I can see the API allows getting Embedded Requesting - https://eversign.com/api/documentation/embedded-requesting#server-side

Is it possible to do this thing via your library?

**Comment by milanlatinovic** [comment]
Hi, yes, this is embedded signing feature, which essentially creates complete signing UI within an iframe.
You can examine this example, https://github.com/eversign/eversign-php-sdk/blob/master/example/iframe.php

There is a line of code which turns on embedded signing
```
$document->setEmbeddedSigningEnabled(true);
```
