### ISSUE TITLE
change uppercase Only to lowercase for eversign api to handle properly

### ISSUE THREAD

**Issue by justinmwood** [eversign/eversign-php-sdk#39]
read only fields were still editable

Readable.php
Line 42
    private $readOnly;
    private $readonly;
Line 45
        $this->readOnly = !!$readOnly;
        $this->readonly = !!$readOnly;
Line 49
        return !!$this->readOnly;
        return !!$this->readonly;

I tested with the above changes and it started working correctly for me.

**Comment by milanlatinovic** [comment]
Hi @justinmwood 

Firstly, thanks for reporting this, much appreciated.
I made a fix and made a new release here https://github.com/eversign/eversign-php-sdk/releases/tag/1.19.1

All best and stay safe! :)
Milan
