### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by serbanrobu** [eversign/eversign-php-sdk#43]
PHP ^7.1 is required to use this package.

Are you planning to support PHP 8?

Thank you!

**Comment by milanlatinovic** [comment]
Hi @serbanrobu, yes there is currently an open pull-request for this
https://github.com/eversign/eversign-php-sdk/pull/42

**Comment by milanlatinovic** [comment]
Hi @serbanrobu , new release of our SDK with support for PHP 8.x is created today.
https://github.com/eversign/eversign-php-sdk/releases/tag/1.21.0

I will close this issue now.

Thanks for commenting, stay safe!
