### ISSUE TITLE
Required parameter $accessKey follows optional parameter $httpType

### ISSUE THREAD

**Issue by serbanrobu** [eversign/eversign-php-sdk#44]
**Describe the bug**
In PHP 8.0 required parameters after optional parameters in function/method signatures are deprecated. [View source](https://php.watch/versions/8.0/deprecate-required-param-after-optional).

**To Reproduce**
Instantiate [Eversign\ApiRequest](https://github.com/eversign/eversign-php-sdk/blob/master/sdk/Eversign/ApiRequest.php#L63).

**Additional context**
eversign-php-sdk version: 1.21.0
PHP version: 8.0

**Solution**
I think deleting the default value for [$httpType](https://github.com/eversign/eversign-php-sdk/blob/master/sdk/Eversign/ApiRequest.php#L63) should solve the problem.

**Comment by milanlatinovic** [comment]
@serbanrobu thanks for reporting this. Yes indeed, ApiRequest constructor has httpType as optional, followed by the required methods, which is not supported in PHP 8.0

I checked places in code where we instantiate ApiRequest object, 12 usages, and none of them relies on default parameter value. 

So yes, this will fix it for sure. I will make a new release today. Thanks!

**Comment by milanlatinovic** [comment]
@serbanrobu please find the latest release with this bugfix here
https://github.com/eversign/eversign-php-sdk/releases/tag/1.21.1

If you experience any further issues when using our SDK with PHP 8, please report it and we will resolve it. 

All best, stay safe! :)
