### ISSUE TITLE
Missing embedded_claim_url

### ISSUE THREAD

**Issue by petrox81** [eversign/eversign-php-sdk#46]
Hello,

param **embedded_claim_url** is not available in RESPONSE for this request:

https://eversign.com/api/documentation/embedded-requesting

REQUEST:

    $client = new Client($API_KEY, $businessId);

    $document = new Document();

    $document->setIsDraft(true);
    $document->setEmbeddedSigningEnabled(true);

    $path = $_FILES['file']['tmp_name'];
    $b64Doc = chunk_split(base64_encode(file_get_contents($path)));

    $file = new File();
    $file->setName($_FILES['file']['name']);
    $file->setFileBase64($b64Doc);

    $document->appendFile($file);

    $signers_arr = array(1=>array("name"=>"Firmatario 1","email"=>"email1@xxxxxxx.it"),2=>array("name"=>"Firmatario Finale","email"=>"agente@xxxxxxxx.it"));

    $sign_order = 1;
    foreach($signers_arr as $signer_id=>$doc_signer){
        $signer = new Signer();
        $signer->setId($signer_id);
        $signer->setName($doc_signer['name']);
        $signer->setEmail($doc_signer['email']);
	    $signer->setLanguage('it');
        $signer->setOrder($sign_order);
        $sign_order++;
	    if(isset($doc_signer['pin']) && $doc_signer['pin'] != "") $signer->setPin($doc_signer['pin']);
        $document->appendSigner($signer);
    }

    $last_element = end($signers_arr);

    $document->setCustomRequesterEmail($last_element['email']);
    $document->setCustomRequesterName($last_element['name']);

    $document->setTitle("TEST");

    $newlyCreatedDocument = $client->createDocument($document);

    var_dump($newlyCreatedDocument);

**Comment by milanlatinovic** [comment]
Dear @petrox81,

Thanks you for reporting this and providing proper example.

I have examined it and indeed, our Document model was not supporting embedded_claim_url.
I extended Document model with this field and it is now properly visible in the response.

This fix is available in the latest release
https://github.com/eversign/eversign-php-sdk/releases/tag/1.22.0

Once again, thanks for contributing by reporting this issue and for using eversign PHP SDK!

All best and stay safe!
