### ISSUE TITLE
Document Template Create

### ISSUE THREAD

**Issue by maheshmbisen** [eversign/eversign-php-sdk#53]
Greetings, 

Is it possible to create a document template using this SDK in Laravel. 

I am asking for https://eversign.com/api/documentation/methods#create-template

Thank you!

**Comment by milanlatinovic** [comment]
Dear @maheshmbisen,

Our SDK does support document template creation according to https://eversign.com/api/documentation/methods#create-template. As publicly and widely adopted PHP SDK we are not focusing on specific or depending of specific frameworks. 

Kind regards,
Milan
