### ISSUE TITLE
Add Declined Reason to Signer object

### ISSUE THREAD

**Issue by Trimasel** [eversign/eversign-php-sdk#54]
**No declined reason text is provided in sdk, however it exist in API response**
`declined_reason` exist inside signer object by call GET https://api.eversign.com/document

**Solution I would like to see, add something similar inside \Eversign\Signer :**
```
    /**
     * Decline reason of Signer
     * @var string
     * @Type("string")
     */
    private $declinedReason = "";

    public function getDeclinedReason()
    {
        return $this->declinedReason;
    }

    public function setDeclinedReason($declinedReason)
    {
        $this->declinedReason = $declinedReason;
    }
```

**Additional information**
https://eversign.com/api/documentation/methods#get-document-template API documentation doesn't have description of `declined_reason` and `declined_timestamp` in specification, however it exist in real response, if `declined` is equal 1

**Comment by milanlatinovic** [comment]
Hello @Trimasel ,

Thank you for reporting this. I made a new release to extend Signer model with declined_reason. You should be able to use setter and getter normally now.

Please check out the latest SDK release, https://github.com/eversign/eversign-php-sdk/releases/tag/1.24.3

Also, I will extend our public API documentation to cover the declined_reason description.

Kind regards,
Milan
