### ISSUE TITLE
Guzzle (curl) Timeout

### ISSUE THREAD

**Issue by hesa2020** [eversign/eversign-php-sdk#58]
**Describe the bug**
GuzzleHttpClient times out after 30 seconds on large documents.

**To Reproduce**
Create a large PDF document with a few signatures, ( $client->createDocument($document); ) 
Notice if it takes more than 30 seconds to upload the document it will fail with a timeout error.

**Expected behavior**
Large document should be able to upload fine.

**Additional context**
Editing the "SDK Config.php file line 20 to: const GUZZLE_TIMEOUT = 3600; fixes it, however this line should be configurable from outside the "vendor" folder to make sure it doesnt break after a composer update.

**Comment by milanlatinovic** [comment]
Hi @hesa2020 , thanks for reporting this.
True, guzzle request timeout should be configurable for sure.

I made MR proposal for this, as soon as it is approved I'll make a new SDK release: https://github.com/eversign/eversign-php-sdk/pull/59

In short, I have extended both ApiRequest and Client with $apiRequestTimeout so it is configurable now. I kept 30s as a default setting. You can create client object with custom timeout now.
```
// Client with custom API request timeout
$client = new Client($config['accessKey'], $config['businessId'], null, 100);
```

**Comment by milanlatinovic** [comment]
You can find the latest release here
https://github.com/eversign/eversign-php-sdk/releases/tag/v1.25.0

Kind regards,
Milan
