### ISSUE TITLE
Can't cancel document with sdk

### ISSUE THREAD

**Issue by Trimasel** [eversign/eversign-php-sdk#60]
**Bug**
Can't cancel document with sdk using cancel/delete document methods

**To Reproduce**
Any call of this methods:
`\Eversign\Client::cancelDocument`
`\Eversign\Client::deleteDocument`
Rise guzzle error due to not correctly send parameters to `\Eversign\ApiRequest::__construct` . This call is missing $payLoad parameter

**Possible solution**
Add $payLoad parameter as in all other methods used in client
```
        $request = new ApiRequest(
            "DELETE",
            $this->accessKey,
            Config::DOCUMENT_URL,
            "Eversign\Result",
            $parameters,
+           null,
            $this->apiBaseUrl,
            $this->apiRequestTimeout
        );
```

**Versions**
 eversign/eversign-php-sdk - 1.25.0

**Comment by milanlatinovic** [comment]
Hi @Trimasel , thanks for reporting this.
In the version 1.25.0, ApiRequest was extended but not all instances of `new ApiRequest(..` were properly modified.
I checked it now and the only affected function is deleteDocument() and cancelDocument() wrapper as you reported.

I'll push a fix now.

**Comment by milanlatinovic** [comment]
I made a 1.25.1 release including the fix
https://github.com/eversign/eversign-php-sdk/releases/tag/1.25.1
