### ISSUE TITLE
Typo in Document and Signer

### ISSUE THREAD

**Issue by Snowbaha** [eversign/eversign-php-sdk#65]
To avoid issue with some IDE / Framework, we should fix the Typo of Document and Signer with Getter.
To keep a logic with CamelCase and not mixed of CC ans Snake.

![image](https://user-images.githubusercontent.com/3284722/172875519-c8d7e400-ecea-44af-8fde-aec193f54b4d.png)

**Comment by milanlatinovic** [comment]
Done, released in https://github.com/eversign/eversign-php-sdk/releases/tag/1.25.4
