### ISSUE TITLE
Feature : add the function downloadFinalDocument()

### ISSUE THREAD

**Issue by Snowbaha** [eversign/eversign-php-sdk#66]
To add he possibility  to stream the result of PDF document or to get the direct URL.

I added the condition with a "[stream](https://docs.guzzlephp.org/en/stable/request-options.html#stream)" payload. I think if we keep this logic, we have to refactor `startRequest()`
The idea is there, you can change if needed :)

[Related to this old PR, I have to separate it](https://github.com/eversign/eversign-php-sdk/pull/63/files).

**Comment by milanlatinovic** [comment]
Nice one, approved and merged.
Released in [1.26.0](https://github.com/eversign/eversign-php-sdk/releases/tag/1.26.0)
