### ISSUE TITLE
Use of deprecated functions of doctrine/annotation

### ISSUE THREAD

**Issue by Akecel** [eversign/eversign-php-sdk#74]
**Describe the bug**

Hello !

After updating all the dependencies of our project, I discovered a bug related to your repository.
The bug happens when using the EverSign client and concerns a deprecated function present in `doctrine/annotation`

```
Call to undefined method Doctrine\Common\Annotations\AnnotationRegistry::registerLoader()
```

After some research, I noticed that the `registerLoader()` function was deprecated since version `2.0.0` of `doctrine/annotation` as you can see here :

- Realase : https://github.com/doctrine/annotations/releases/tag/2.0.0
- Commit : https://github.com/doctrine/annotations/pull/468/files

On a quick search, I saw that you don't integrate `doctrine/annotation` directly into your dependencies, but rely on `jms/serializer` for that. Unfortunately, for two weeks now, a new version of `jms/serializer` is available being compatible with the version `2.0.0` of `doctrine/annotation`, which inevitably, poses problem because you pass by this dependence to reach `doctrine/annotation` and that you authorize the use of the last version in date, your code thus uses a function being deprecated.

You can find here the relevant release of `jms/serializer` : 
- https://github.com/schmittjoh/serializer/releases/tag/3.19.0

Here is the exact place where you use this deprecated function (you may use it elsewhere) : 
- https://github.com/eversign/eversign-php-sdk/blob/master/sdk/Eversign/Client.php#L76

I think it would be more interesting for you to integrate directly `doctrine/annotation` in your dependencies to keep more control on the breaking change due to the different release. 
Or at least lock a version of `jms/serializer` to a version compatible with your system until you can rework this part of your logic and thus in accordance with the news of `doctrine/annotation`.

**To Reproduce**

Use the EverSign client with a fresh `composer update`
- `eversign-php-sdk` : `1.26.2`
     - `jms/serializer` : `> 3.19.0`
         - `doctrine/annotation` : `> 2.0.0`

```php
$client = new Client(
       config('services.eversign.key'),
      config('services.eversign.id')
);
```

Error 500 ➡️ `Call to undefined method Doctrine\Common\Annotations\AnnotationRegistry::registerLoader()`

**System :**

The connection to the client (and thus the error) is done in a Laravel Job
- Laravel 9
- Vapor
- PHP 8.1

Let me know if you need more information

**Additional context**

We could certainly block `jms/serializer` to a certain version in our lock but it would require us to be very careful at each update to go back specifically for this package to avoid that this problem occurs again and it seemed important to me to report this problem that seems to be present for 2 weeks and may affect other users of your SDK.

**Comment by milanlatinovic** [comment]
Hi @Akecel ,

Thanks for reporting this and doing the initial research, nice one! :) 
I managed to replicate this locally as well.

I believe that the best approach is to fix doctrine/annotations to 1.9 versions, with `"doctrine/annotations": "^1.9"`.

I made a pull request here https://github.com/eversign/eversign-php-sdk/pull/75 , can you check out if this is working for you.
I already tested it and successfully generated a document after running the latest "composer update"

Once we merge this I'll create a new version of SDK client.

Thanks!

**Comment by Akecel** [comment]
@milanlatinovic Looks good to me ! Thank you 😉

**Comment by milanlatinovic** [comment]
Thanks! Merged and I made new release here
https://github.com/eversign/eversign-php-sdk/releases/tag/1.27.0

Have fun! :)
