### ISSUE TITLE
Sandbox mode?

### ISSUE THREAD

**Issue by valentinfily** [eversign/eversign-php-sdk#8]
I couldn't find how to use the sandbox mode with the PHP SDK. Is it possible?

**Comment by dominikkukacka** [comment]
We will be pushing a fix to add this mode shortly.

**Comment by dominikkukacka** [comment]
we just pushed 1.5.0 which introduces the `$document->setSandbox(true);` and `$documentTemplate->setSandbox(true);`
😄

**Comment by valentinfily** [comment]
Brilliant!
