### ISSUE TITLE
Canceling Document

### ISSUE THREAD

**Issue by Micsou** [eversign/eversign-php-sdk#9]
Hi, 
I want to cancel a document via your API. 
The Client cancelDocument function calls the deleteDocument function which test if document is draft or is cancelled. 

Does it mean that only draft documents can be canceled ? Or is that a bug that means I can never cancel document ? 

When I go on your Application, I can cancel a document even if it's not draft. 

Thanks by advance for your help. 
Michael

**Comment by dominikkukacka** [comment]
Yes you are right you can only cancel and delete draf documents.
I also pushed a fix for the cancel/delete functionality in 1.10.0.
